name: Build Kivy APK with FFpyplayer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          openjdk-17-jdk \
          unzip \
          zip \
          autoconf \
          automake \
          libtool \
          pkg-config \
          ccache \
          libncursesw5-dev \
          libsqlite3-dev \
          sqlite3 \
          libgdbm-dev \
          libgdbm-compat-dev \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0"
        pip install buildozer

    # Жестко прописываем одобренные лицензии Google, чтобы sdkmanager вообще не задавал вопросов
    - name: Inject Android SDK Licenses
      run: |
        mkdir -p ~/.android/licenses
        mkdir -p .buildozer/android/platform/android-sdk/licenses
        
        # Хэши официальных лицензий Android SDK
        LICENSE_HASHES="24333f8a63b6825ea9c5514f83c2829b004d1fee\n8933bad161af4178b1185d1a37fbf41ea5269c55\n84831b9409646a918e30573bab4c9c91346d8abd\n79a253134b6ddda86869817f9152dc0ede77ea5a\nd975f751698a77b662f1254ddbeed39cba18573d"
        
        echo -e "$LICENSE_HASHES" > ~/.android/licenses/android-sdk-license
        echo -e "$LICENSE_HASHES" > .buildozer/android/platform/android-sdk/licenses/android-sdk-license

    # Запуск чистой сборки. Зафиксированные build-tools 33.0.1 скачаются молча
    - name: Build Android APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-debug
        path: bin/*.apk
